# Generated by Django 4.2 on 2023-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='id',
        ),
        migrations.AddField(
            model_name='issues',
            name='issue_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
